# ifitwala_ed/schedule/api/calendar/quick_create/constants.py

from __future__ import annotations

import frappe

QUICK_CREATE_IDEMPOTENCY_TTL_SECONDS = 900
META_SELECT_OPTIONS_CACHE_TTL_SECONDS = 3600
QUICK_CREATE_OPTIONS_CACHE_TTL_SECONDS = 300
ATTENDEE_SEARCH_CACHE_TTL_SECONDS = 60
SLOT_SUGGESTION_CACHE_TTL_SECONDS = 60
MAX_ATTENDEE_SEARCH_RESULTS = 12
MAX_SLOT_SUGGESTIONS = 5
MAX_SLOT_FALLBACKS = 3
MAX_SLOT_ATTENDEES = 20
MAX_SLOT_SEARCH_DAYS = 14
SLOT_INCREMENT_MINUTES = 15
DEFAULT_DAY_START_TIME = "08:00:00"
DEFAULT_DAY_END_TIME = "17:00:00"
VIRTUAL_ORGANIZATION_ROOT = "All Organizations"


class StudentAvailabilityConflictError(frappe.ValidationError):
    pass
