/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PortalFooter: typeof import('./src/components/PortalFooter.vue')['default']
    PortalNavbar: typeof import('./src/components/PortalNavbar.vue')['default']
    PortalSidebar: typeof import('./src/components/PortalSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
